# UCS420: Cognitive Computing
## Assignment 5 – NumPy-Introduction-1

## Q1. Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: 

### a) Addition of 2 in all the elements

In [45]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = arr + 2
print(result)

[12 22 32 42 52]


### b) Multiply 3 with all the elements

In [46]:
result = arr * 3
print(result)

[ 30  60  90 120 150]


### c) Divide every element by 2

In [47]:
result = arr / 2
print(result)

[ 5. 10. 15. 20. 25.]


## Q2. Basic NumPy Array

### a) Reverse the NumPy array

In [48]:
arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


### b) Find the most frequent value and its indices

In [49]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]


In [50]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 1 2]


## Q3. Access Elements from a 2-D Array

In [51]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


## Q4. NumPy Array Using `linspace()`

In [52]:
Harsh = np.linspace(10, 100, 25)

print("Array:", Harsh)
print("Dimensions:", Harsh.ndim)
print("Shape:", Harsh.shape)
print("Total elements:", Harsh.size)
print("Data type:", Harsh.dtype)
print("Total bytes:", Harsh.nbytes)

transpose_Harsh = Harsh.reshape(25, 1)
print("\nTranspose using reshape():")
print(transpose_Harsh)

print("\nTranspose using T attribute:")
print(Harsh.T)

print("\nCan T be used directly?")
print("For a 1-D NumPy array, .T does not change its shape.")
print("It returns the same 1-D array. Use reshape(25, 1) for a column form.")

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Can T be used directly?
For a 1-D NumPy array, .T does not change its shape.
It returns the same 1-D array. Use reshape(25, 1) for a column form.


## Q5. NumPy 2-D Array Operations

In [53]:
ucs420_Harsh = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Array:")
print(ucs420_Harsh)

print("\nMean:", np.mean(ucs420_Harsh))
print("Median:", np.median(ucs420_Harsh))
print("Maximum:", np.max(ucs420_Harsh))
print("Minimum:", np.min(ucs420_Harsh))
print("Unique elements:", np.unique(ucs420_Harsh))

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [54]:
reshaped_ucs420_Harsh = ucs420_Harsh.reshape(4, 3)

print("Reshaped array (4 x 3):")
print(reshaped_ucs420_Harsh)

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [55]:
resized_ucs420_Harsh = np.resize(ucs420_Harsh, (2, 3))

print("Resized array (2 x 3):")
print(resized_ucs420_Harsh)

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
